### PR TITLE
Add <code> element inside <pre> in code block

### PR DESCRIPTION
**Pull request by johnfraney**
Adds a nested `<code>` element for the block/pre code plugin for more semantic
HTML.

### CODE REVIEW

**Comment by johnfraney** [comment]
Closes #54

**Comment by johnfraney** [comment]
Here's a working example of this change:
screenshot from 2018-08-18 13-51-16

**Comment by filwaitman** [comment]
Hi @johnfraney! Thanks for the PR!

This looks good to me. @kinkerl can you take a look as well?

**Comment by johnfraney** [comment]
@filwaitman Happy to help!

**Comment by didierCH** [comment]
@johnfraney thank you for this feature. It's super useful.

**Comment by johnfraney** [comment]
@didierCH You're welcome. Take care!

**Pull request merged**
