### PR TITLE
#101, use proper iconset prefix in ckeditor preview

### PR DESCRIPTION
**Pull request by sq9mev**

### CODE REVIEW

**Comment by FinalAngel** [comment]
@sq9mev this appears to change only the compiled file, could you make the change in the source file?

**Comment by sq9mev** [comment]
@FinalAngel well, now i see it's build with webpack… unfortunelly i'no not familiar with it… actually i could just modify blindly the source as the change is small, but let me do that right way (using wepback), patch will be provided soon.

**Comment by FinalAngel** [comment]
thank you very much, I'll have a look at it in the next days :)

**Review by corentinbettiol — APPROVED** [review]
:+1:

**Comment by FinalAngel** [comment]
@sq9mev just got to it and the commit fixes the problem. Thank you!

**Review by FinalAngel — APPROVED** [review]

**Pull request merged**
