### PR TITLE
chore: Prepare release 3.0.2

### PR DESCRIPTION
**Pull request by fsbraun**
## Related resources

* #...
* #...

## Checklist

* [ ] I have opened this pull request against ``master``
* [ ] I have added or modified the tests when changing logic
* [ ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by leture** [comment]
@fsbraun Hi, is there an ETA for the release? I am asking because it would be very helpful for me when there would a new release containing the fix for https://github.com/django-cms/djangocms-bootstrap4/issues/163.

**Comment by fsbraun** [comment]
@leture Thanks for reminding me. Sorry, this somehow fell off my list.

**Comment by fsbraun** [comment]
Out now.

**Comment by leture** [comment]
Thank you very much for your immediate response.

**Pull request merged**
